deleteDependentEntities: true
createMissingRelatedEntities: true
resources:
  - kind: project
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: '.uuid | gsub("[{-}]"; "")'
          title: .name
          blueprint: '"bitbucketProject"'
          properties:
            url: '.links.html.href'
  - kind: repository
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: '.uuid | gsub("[{-}]"; "")'
          title: .name
          blueprint: '"bitbucketRepository"'
          properties:
            url: '.links.html.href'
            scm: .scm
            language: .language
            description: .description
          relations:
            project: '.project.uuid | gsub("[{-}]"; "")'

  - kind: pull-request
    selector:
      query: "true"
    port:
      entity:
        mappings:
          identifier: '(.destination.repository.uuid | gsub("[{-}]"; "")) + (.id|tostring)'
          title: .title
          blueprint: '"bitbucketPullRequest"'
          properties:
            state: .state
            author: '.author.display_name'
          relations:
            repository: '.destination.repository.uuid | gsub("[{-}]"; "")'